### ISSUE TITLE
Error in file.exists(vcf.file) : object 'test.vcf.gz' not found

### ISSUE THREAD

**Issue by dzaccook** [timflutre/rutilstimflutre#21]
Hi,
I test the script, vcf2dosage(test.vcf.gz,genome = "test",gdose.gz,ca.gz), and get an error below,
Error in file.exists(vcf.file) : object 'test.vcf.gz' not found.
what is the correct command?
thank you!

**Comment by timflutre** [comment]
The error message means that R can't find the VCF file in the current directory. As indicated in the help of the function (available via `?vcf2dosage`), you need to give the path to the VCF file so that R can find it.
