### ISSUE TITLE
problem installing rutilstimflutre

### ISSUE THREAD

**Issue by amarrano** [timflutre/rutilstimflutre#36]
Hi,

When I try to install the package using devtools, I get the following error:

Downloading GitHub repo timflutre/rutilstimflutre@master
timflutre-rutilstimflutre-354976e/COPYING: Can't create '\\\\?\\C:\\Users\\rossa\\AppData\\Local\\Temp\\RtmpyujoRH\\remotes31b46dcb1aed\\timflutre-rutilstimflutre-354976e\\COPYING'
tar.exe: Error exit delayed from previous errors.
√  checking for file 'C:\Users\rossa\AppData\Local\Temp\RtmpyujoRH\remotes31b46dcb1aed\timflutre-rutilstimflutre-354976e/DESCRIPTION' (602ms)
-  preparing 'rutilstimflutre': (2.4s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (2.8s)
-  checking for empty or unneeded directories
-  building 'rutilstimflutre_0.170.0.tar.gz'
   
Installing package into ‘C:/Users/rossa/OneDrive/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'rutilstimflutre' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'data.table' was built under R version 3.5.3
ERROR: lazy loading failed for package 'rutilstimflutre'
* removing 'C:/Users/rossa/OneDrive/Documents/R/win-library/3.5/rutilstimflutre'
In R CMD INSTALL
Error: Failed to install 'rutilstimflutre' from GitHub:
  (converted from warning) installation of package ‘C:/Users/rossa/AppData/Local/Temp/RtmpyujoRH/file31b47baf2a97/rutilstimflutre_0.170.0.tar.gz’ had non-zero exit status
In addition: Warning message:
In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\rossa\AppData\Local\Temp\RtmpyujoRH\file31b45cc4740f.tar.gz" -C "C:/Users/rossa/AppData/Local/Temp/RtmpyujoRH/remotes31b46dcb1aed"’ returned error code 1

I have also tried to install it from the zip file without success.

How can I fix it?

Thank you.

**Comment by timflutre** [comment]
Some people told me that there is an issue with data.table when installing my package on R 3.6.1, but it works well with R 3.6.2.
