### ISSUE TITLE
lmerAM() - names of random effects

### ISSUE THREAD

**Issue by germmtz** [timflutre/rutilstimflutre#37]
It seems that the lmerAM() has been updated with the following verfication:  

`"geno.add" %in% names(relmat). `

To my understanding, this means that the user has to rename one of its random effects "geno.add" to be able to run lmerAM(). I understand that this function is primarily designed for animal models, and so that one of the random effect must contain additive genetic effects, but I wonder weither this might be a constraint for other purposes. One could want to use this function to fit mixed models without additive genetic effects/additive relationship coefficients matrix. 

In sum, this is not really an issue, rather a suggestion. In case you choose to keep this feature, maybe you could mention that one of the random effect must be named "geno.add" in the function help. 

Thank you very much !

**Comment by timflutre** [comment]
It was already in the help, though not very clearly... I improved the help message (https://github.com/timflutre/rutilstimflutre/commit/c7f9089129a1e502c4429b03a33c3fba25f99855).

p.s. : I had to introduce it to compute the (narrow-sense) heritability properly
