### ISSUE TITLE
difficulties with renameVcfSamples function

### ISSUE THREAD

**Issue by rcastil** [timflutre/rutilstimflutre#47]
Hi Tim,
I am sorry to trouble you with an apparent easy-to-use function, but I cannot get my head around it. I always get warnings (not errors) but no new vcf file with the sample names changed. Could you possibly assist me? Below is the description of the commands entered in Rstudio.

vcf filename: populations.snps.vcf
table with old and new sample names: pagellus_91_snpfilt.txt

> ##dataframe with samples names original and new (for SNPfilt)
> pop.91 <- read.table("pagellus_91_snpfilt.txt", sep = "\t", header = FALSE)
> is.data.frame(pop.91)
[1] TRUE
> head(pop.91)
                 V1    V2
1 P01-A01-PABOAZ1_R AZ001
2 P01-A02-PABOAZ2_R AZ002
3 P01-A03-PABOAZ3_R AZ003
4 P01-A04-PABOAZ4_R AZ004
5 P01-A05-PABOAZ5_R AZ005
6 P01-A06-PABOAZ6_R AZ006
> ##replace original samples names for new short names
> renameVcfSamples(
   "/home/rcastil/R/pagellus_stacks_denovo/populations.snps.vcf",
   pop.91,
   "/home/rcastil/R/pagellus_stacks_denovo/",
   skip.check = FALSE,
   sort.variants = FALSE)
[main] Unrecognized command.
Warning messages:
1: In file.remove(out.vcf.file) :
  cannot remove file '/home/rcastil/R/pagellus_stacks_denovo/', reason 'Directory not empty'
2: In renameVcfSamples("/home/rcastil/R/pagellus_stacks_denovo/populations.snps.vcf",  :
  bcftools returned 1

If however I add an empty directory to in.vcf.file, then that directory is deleted and I get;
> renameVcfSamples(
   "/home/rcastil/R/pagellus_stacks_denovo/populations.snps.vcf",
   pop.91,
   "/home/rcastil/R/pagellus_stacks_denovo/new",
   skip.check = FALSE,
   sort.variants = FALSE)
[main] Unrecognized command.
Warning message:
In renameVcfSamples("/home/rcastil/R/pagellus_stacks_denovo/populations.snps.vcf",  :
  bcftools returned 1

Thanks a lot!
Rita

**Comment by timflutre** [comment]
Hi Rita,
The `renameVcfSamples` function uses `bcftools` under the hood and requires to be on GNU/Linux and not Windows (Apple may be ok). Maybe that's a problem?
Run the command, and just after the error, run `traceback()`. Does it give any hint about the cause of the error?
Best,
Tim

**Comment by rcastil** [comment]
Dear Tim,
Thanks for the reply. I am using Ubuntu, that is not the problem. And no success with `traceback()` too, as No traceback available.

So I gather the problem is in the string inside the `bcftools` to return the message; [main] Unrecognized command.
If I do

`system('bcftools')

Program: bcftools (Tools for data in the VCF/BCF formats)
Version: 0.1.19-96b5f2294a

Usage:   bcftools <command> <arguments>

Command: view      print, extract, convert and call SNPs from BCF
         index     index BCF
         cat       concatenate BCFs
         ld        compute all-pair r^2
         ldpair    compute r^2 between requested pairs`

so bcftools is working.

`> system('bcftools reheader')
[main] Unrecognized command.`

So the problem is with the reheader!

I have been looking for a solution but I haven´t found it. However, alternatively, I used Hex Fiend.txt to edit the VCF file and copy+paste the names of the samples.

Thanks for your assistance,
Rita

**Comment by timflutre** [comment]
Thanks Rita for these details.

On my computer on Ubuntu:
```
$ bcftools --version
bcftools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
...

$ bcftools reheader

About:   Modify header of VCF/BCF files, change sample names.
Usage:   bcftools reheader [OPTIONS] <in.vcf.gz>

Options:
    -h, --header <file>     new header
    -o, --output <file>     write output to a file [standard output]
    -s, --samples <file>    new sample names
        --threads <int>     number of extra compression threads (BCF only) [0]
```

Good luck with your work!
