### ISSUE TITLE
Make kinship matrices symmetric

### ISSUE THREAD

**Issue by germmtz** [timflutre/rutilstimflutre#48]
It happens that kinship matrices created by `estimGenRel()` (maybe also the case with other functions from the package) are not symmetric due to machine precision (e.g., difference between upper and lower triangles are < 10E-16). This can be problematic for other packages that only accept symmetric matrices. Since a kinship matrix is supposed to be symmetric anyway, it would be nice to update the function to make the output matrix always symmetric. A simple option could be:

`A[lower.tri(A)] <- t(A)[lower.tri(t(A))]`

Thanks :)

Germain

**Comment by timflutre** [comment]
Sorry! Now fixed in commit [60979d2](https://github.com/timflutre/rutilstimflutre/commit/60979d2759c53af087ae1d2eb2fb22653a41c0e0).
