### ISSUE TITLE
Conflict with shiny "em" function (="em" html tag)

### ISSUE THREAD

**Issue by juliendiot42** [timflutre/rutilstimflutre#8]
Hi !
The "em" function of the package can be in conflict with the corresponding function from the "shiny" package.
see commit of Apr 5, 2018 : minor improvement to em()

It is not very important but it can raise an error, witch is a bit hard to find, in some shiny app.

**Comment by timflutre** [comment]
Let's say there are two functions "myfunc", one from package "pkgA" and one fro package "pkgB". Let's also say that we are writing a Shiny interface importing both packages. There is no conflict as long as one uses the following syntax:

    myvar1 <- pkgA::myfunc()
    myvar2 <- pkgB::myfunc()

Therefore, I won't change the "em" function from the "rutilstimflutre" package. In fact, one should rather use `shiny::em(...)` in the Shiny interface. This also makes me think that it could be better to transform the current Shiny interface into a proper R package (see [issue 8](https://github.com/timflutre/PlantSelBreedGame/issues/8)).

**Comment by timflutre** [comment]
Hi @juliendiot42 ! For your information, in the latest release (0.160.5), I renamed the `em` function into `em_solve`. But this is not a reason to ignore [issue #11](https://github.com/timflutre/PlantSelBreedGame/issues/11) of PlantSelBreedGame ;)

**Comment by juliendiot42** [comment]
Hi !
Good, I think it's better. Even if it's possible to manage easily this kind of issue, most people don't use the syntax ``pkg::function()`` very often, just to when conflicts appear.

Another method to handle this kind of conflict is to pay attention to the order of the packages loading. The last package overwrite the functions of the previous one in the global environment. By this way, it's possible to manage the "priority" of each packages.

For the [issue #11](https://github.com/timflutre/PlantSelBreedGame/issues/11), of course it's not a reason ( but it will be a long and boring task  to do :satisfied:  )

**Comment by timflutre** [comment]
Caution, the ONLY way of taking care of this thing when developing a package is to use the syntax `pkg::function()`. It's cumbersome but compulsory, otherwise `R CMD check` returns an error.
